const OPS = require('bitcoin-ops');

OPS.OP_CHECKSAFEMULTISIG = 186;
OPS.OP_CHECKTHREAD = 187;

OPS.OP_ISSUEKEYADD = 189;
OPS.OP_ISSUEKEYREVOKE = 190;
OPS.OP_PROVISIONKEYADD = 191;
OPS.OP_PROVISIONKEYREVOKE = 192;
OPS.OP_VALIDATEKEYADD = 193;
OPS.OP_VALIDATEKEYREVOKE = 194;
OPS.OP_ASPKEYADD = 195;
OPS.OP_ASPKEYREVOKE = 196;

module.exports = OPS;
